
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python
  namespace: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-python
  template:
    metadata:
      labels:
        app: backend-python
    spec:
      containers:
        - name: backend-python
          image: anubhav1804/backend-python:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000


